package pkgfinal.project;

import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkgfinal.project.AddNewAccount.AddNewAccount;

public class AddNewAccountJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddNewAccountJFrame
     */
    public AddNewAccountJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NamejLabel = new javax.swing.JLabel();
        EmailjLabel = new javax.swing.JLabel();
        TelephoneNumberjLabel = new javax.swing.JLabel();
        typejLabel = new javax.swing.JLabel();
        AddNewAccountjLabel = new javax.swing.JLabel();
        FieldNamejText = new javax.swing.JTextField();
        TelephoneNumberjTextField = new javax.swing.JTextField();
        EmailjTextField = new javax.swing.JTextField();
        TypejComboBox = new javax.swing.JComboBox<>();
        AddAccountjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        NamejLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NamejLabel.setText("Name");

        EmailjLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        EmailjLabel.setText("E-mail");

        TelephoneNumberjLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        TelephoneNumberjLabel.setText("Tel no ");

        typejLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        typejLabel.setText("Type");

        AddNewAccountjLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        AddNewAccountjLabel.setText("Add New Account");

        FieldNamejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNamejTextActionPerformed(evt);
            }
        });

        TypejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current", "Savings" }));
        TypejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypejComboBoxActionPerformed(evt);
            }
        });

        AddAccountjButton.setText("Add Account");
        AddAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAccountjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TelephoneNumberjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(333, 333, 333))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(356, 356, 356))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EmailjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(127, 127, 127))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(typejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(49, 49, 49)
                                .addComponent(TypejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(206, 206, 206))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddNewAccountjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TelephoneNumberjTextField)
                                    .addComponent(EmailjTextField)
                                    .addComponent(FieldNamejText))
                                .addGap(56, 56, 56)))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(AddAccountjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddNewAccountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(NamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(FieldNamejText)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(EmailjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(EmailjTextField)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(TelephoneNumberjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TelephoneNumberjTextField)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(typejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TypejComboBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddAccountjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypejComboBoxActionPerformed

    private void FieldNamejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNamejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNamejTextActionPerformed

    private void AddAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAccountjButtonActionPerformed
        String Name;
        String Email;
        String PhoneNumber;
        Name = FieldNamejText.getText();
        Email = EmailjTextField.getText();
        PhoneNumber = TelephoneNumberjTextField.getText();
        Object[] type;
        String s;
        if (InputValidation.UernameAddNewAccount(Name)) {
            if (InputValidation.eMailValidation(Email)) {
                if (InputValidation.telephoneVerification(PhoneNumber)) {

                    if (evt.getSource() == AddAccountjButton) {
                        try {
                            type = TypejComboBox.getSelectedObjects();
                            s = Arrays.toString(type);
                            AddNewAccount(Name, Email, PhoneNumber, s);
                            AddNewAccountJFrame.this.dispose();
                            new HomeScreenJFrame().setVisible(true);
                        } catch (Exception ex) {
                            Logger.getLogger(AddNewAccountJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid phone number", "Message", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a valid email", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter your First and Last name", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddAccountjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewAccountJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAccountjButton;
    private javax.swing.JLabel AddNewAccountjLabel;
    private javax.swing.JLabel EmailjLabel;
    private javax.swing.JTextField EmailjTextField;
    private javax.swing.JTextField FieldNamejText;
    private javax.swing.JLabel NamejLabel;
    private javax.swing.JLabel TelephoneNumberjLabel;
    private javax.swing.JTextField TelephoneNumberjTextField;
    private javax.swing.JComboBox<String> TypejComboBox;
    private javax.swing.JLabel typejLabel;
    // End of variables declaration//GEN-END:variables
}
