package pkgfinal.project;

import javax.swing.*;
import static pkgfinal.project.ModifyAccount.accountnumber;
import static pkgfinal.project.ModifyDeposit.ModifyAccount;
import java.time.LocalDateTime;

public class DepositJFrame extends javax.swing.JFrame {

    public DepositJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumberJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AmountToBeDepositedJTextField = new javax.swing.JTextField();
        DepositJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Deposit");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Account Number");

        accountNumberJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountNumberJTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Amount to be deposited ");

        DepositJButton.setText("Submit");
        DepositJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AmountToBeDepositedJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(accountNumberJTextField))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DepositJButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accountNumberJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AmountToBeDepositedJTextField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(DepositJButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountNumberJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountNumberJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountNumberJTextFieldActionPerformed

    private void DepositJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositJButtonActionPerformed
        LocalDateTime currentTime = LocalDateTime.now();
        String currentT = String.valueOf(currentTime);
        String accountNumber;
        String amountToBeDeposited;
        accountNumber = accountNumberJTextField.getText();
        amountToBeDeposited = AmountToBeDepositedJTextField.getText();

        if (InputValidation.accountNumberValidation(accountNumber)) {
            if (InputValidation.moenyvalidation(amountToBeDeposited)) {
                
                
                
                if (evt.getSource() == DepositJButton) {

            double amount = Double.parseDouble(amountToBeDeposited);

            try {
                boolean checkValidation = Account.validateAccountExcistance(accountNumber);
                if (checkValidation == false) {
                    JOptionPane.showMessageDialog(this, "Non excisting account.", "Message", JOptionPane.ERROR_MESSAGE);
                } else if (checkValidation == true) {
                    if (amount > 10000.0) {
                        JOptionPane.showMessageDialog(this, "Amount deposited exceeds 10K$, please deposit less.", "Message", JOptionPane.INFORMATION_MESSAGE);
                    } else if (amount > 0.0) {
                        //modify men giovanni
                        //accountNumber, amountToBeDeposited

                        //System.out.println(amount);
                        ModifyAccount(amountToBeDeposited, accountNumber);

                        //date returned by giovanni same date modified in accountG.txt 
                        Transaction.AddTransactionInfo("deposit", amountToBeDeposited, accountNumber, currentT);
                    } else {
                        JOptionPane.showMessageDialog(this, "Incorrect Amount", "Message", JOptionPane.INFORMATION_MESSAGE);
                    }
                }

            } catch (Exception e) {
                System.out.println("Error 404");
            }

            //System.out.println(amount);
        }
        super.dispose();
        new HomeScreenJFrame().setVisible(true);
                
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Input a valid amount", "Message", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Input a valid account", "Message", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_DepositJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountToBeDepositedJTextField;
    private javax.swing.JButton DepositJButton;
    private javax.swing.JTextField accountNumberJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
