package pkgfinal.project;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class HomeScreenJFrame extends javax.swing.JFrame {

    public HomeScreenJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addNewAccountJButton = new javax.swing.JButton();
        modifyAccountJbutton = new javax.swing.JButton();
        closeAccountJButton = new javax.swing.JButton();
        viewAccountsJButton = new javax.swing.JButton();
        withdrawJButton = new javax.swing.JButton();
        TransferJButton = new javax.swing.JButton();
        applyIntersetJButton = new javax.swing.JButton();
        depositJButton = new javax.swing.JButton();
        searchAccountsJButton = new javax.swing.JButton();
        transactionHistoryJButton = new javax.swing.JButton();
        logoutJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Screen");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to your Home Screen !");

        addNewAccountJButton.setBackground(new java.awt.Color(255, 204, 153));
        addNewAccountJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        addNewAccountJButton.setText("Add New Account");
        addNewAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAccountJButtonActionPerformed(evt);
            }
        });

        modifyAccountJbutton.setBackground(new java.awt.Color(255, 204, 153));
        modifyAccountJbutton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        modifyAccountJbutton.setText("Modify Account");
        modifyAccountJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyAccountJbuttonActionPerformed(evt);
            }
        });

        closeAccountJButton.setBackground(new java.awt.Color(255, 204, 153));
        closeAccountJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        closeAccountJButton.setText("Close Account");
        closeAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAccountJButtonActionPerformed(evt);
            }
        });

        viewAccountsJButton.setBackground(new java.awt.Color(255, 204, 102));
        viewAccountsJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        viewAccountsJButton.setText("View Accounts");
        viewAccountsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAccountsJButtonActionPerformed(evt);
            }
        });

        withdrawJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        withdrawJButton.setText("Withdraw");
        withdrawJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawJButtonActionPerformed(evt);
            }
        });

        TransferJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TransferJButton.setText("Transfer");
        TransferJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferJButtonActionPerformed(evt);
            }
        });

        applyIntersetJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        applyIntersetJButton.setText("Apply Interset");
        applyIntersetJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyIntersetJButtonActionPerformed(evt);
            }
        });

        depositJButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        depositJButton.setText("Deposit");
        depositJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositJButtonActionPerformed(evt);
            }
        });

        searchAccountsJButton.setBackground(new java.awt.Color(255, 204, 102));
        searchAccountsJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        searchAccountsJButton.setText("Search Accounts");
        searchAccountsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAccountsJButtonActionPerformed(evt);
            }
        });

        transactionHistoryJButton.setBackground(new java.awt.Color(255, 204, 102));
        transactionHistoryJButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        transactionHistoryJButton.setText("Transaction History");
        transactionHistoryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionHistoryJButtonActionPerformed(evt);
            }
        });

        logoutJButton.setBackground(new java.awt.Color(51, 51, 0));
        logoutJButton.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        logoutJButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutJButton.setText("Logout");
        logoutJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(closeAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifyAccountJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addNewAccountJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(withdrawJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(TransferJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(depositJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(searchAccountsJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(transactionHistoryJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(viewAccountsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(applyIntersetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewAccountsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(depositJButton)
                            .addComponent(addNewAccountJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(withdrawJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyAccountJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchAccountsJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TransferJButton)
                            .addComponent(transactionHistoryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(closeAccountJButton)))
                .addGap(35, 35, 35)
                .addComponent(applyIntersetJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(logoutJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addNewAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAccountJButtonActionPerformed
        super.dispose();
        AddNewAccountJFrame addNewAccountJFrame = new AddNewAccountJFrame();
        addNewAccountJFrame.setVisible(true);
    }//GEN-LAST:event_addNewAccountJButtonActionPerformed

    private void modifyAccountJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyAccountJbuttonActionPerformed
        super.setVisible(false);
        new AskToModifyAccNoJFrame().setVisible(true);
    }//GEN-LAST:event_modifyAccountJbuttonActionPerformed

    private void closeAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAccountJButtonActionPerformed
        super.dispose();
        new CloseAccountJFrame().setVisible(true);
    }//GEN-LAST:event_closeAccountJButtonActionPerformed

    private void viewAccountsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAccountsJButtonActionPerformed
        super.setVisible(false);
        new ViewAccountsJFrame().setVisible(true);

    }//GEN-LAST:event_viewAccountsJButtonActionPerformed

    private void withdrawJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawJButtonActionPerformed
        super.dispose();        new WithdrawJFrame().setVisible(true);    }//GEN-LAST:event_withdrawJButtonActionPerformed

    private void TransferJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferJButtonActionPerformed
        super.dispose();
        new TransferJFrame().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_TransferJButtonActionPerformed

    private void applyIntersetJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyIntersetJButtonActionPerformed
        ImageIcon icon = new ImageIcon("path/to/your/icon.png");
        try {
            ApplyInterest.doApplyInterest();
        } catch (Exception ex) {
            Logger.getLogger(HomeScreenJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Interest Applied", "Success", JOptionPane.INFORMATION_MESSAGE, icon);

    }//GEN-LAST:event_applyIntersetJButtonActionPerformed

    private void depositJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositJButtonActionPerformed
        super.dispose();
        new DepositJFrame().setVisible(true);
    }//GEN-LAST:event_depositJButtonActionPerformed

    private void searchAccountsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchAccountsJButtonActionPerformed
        SearchAccountsJFrame searchAccountsJFrame = new SearchAccountsJFrame();
        searchAccountsJFrame.setVisible(true);
        super.setVisible(false);
    }//GEN-LAST:event_searchAccountsJButtonActionPerformed

    private void transactionHistoryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionHistoryJButtonActionPerformed
        new TransactionHistoryAccountNumberJFrame().setVisible(true);
        super.dispose();
    }//GEN-LAST:event_transactionHistoryJButtonActionPerformed

    private void logoutJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutJButtonActionPerformed
        HomeScreenJFrame.this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);

    }//GEN-LAST:event_logoutJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreenJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreenJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransferJButton;
    private javax.swing.JButton addNewAccountJButton;
    private javax.swing.JButton applyIntersetJButton;
    private javax.swing.JButton closeAccountJButton;
    private javax.swing.JButton depositJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logoutJButton;
    private javax.swing.JButton modifyAccountJbutton;
    private javax.swing.JButton searchAccountsJButton;
    private javax.swing.JButton transactionHistoryJButton;
    private javax.swing.JButton viewAccountsJButton;
    private javax.swing.JButton withdrawJButton;
    // End of variables declaration//GEN-END:variables

}
