/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkgfinal.project.Account.validateAccountExcistance;
import static pkgfinal.project.ModifyAccount.ModifyAccount;


public class ModifyAccountJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ModifyAccountJFrame
     */
    public ModifyAccountJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModifyefAccountjButton = new javax.swing.JButton();
        modifyedNamejLabel = new javax.swing.JLabel();
        modifyedEmailjLabel = new javax.swing.JLabel();
        modifyedTelephoneNumberjLabel = new javax.swing.JLabel();
        ModifyAccountjLabel = new javax.swing.JLabel();
        ModifyedNamejTextField = new javax.swing.JTextField();
        ModifyedTelephoneNumberjTextField = new javax.swing.JTextField();
        ModifyedEmailjTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ModifyefAccountjButton.setText("Confirm changes");
        ModifyefAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyefAccountjButtonActionPerformed(evt);
            }
        });

        modifyedNamejLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        modifyedNamejLabel.setText("Name");

        modifyedEmailjLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        modifyedEmailjLabel.setText("E-mail");

        modifyedTelephoneNumberjLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        modifyedTelephoneNumberjLabel.setText("Tel no ");

        ModifyAccountjLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        ModifyAccountjLabel.setText("Modify Account");

        ModifyedNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyedNamejTextFieldActionPerformed(evt);
            }
        });

        ModifyedEmailjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyedEmailjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(ModifyAccountjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modifyedTelephoneNumberjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyedNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyedEmailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ModifyedEmailjTextField)
                            .addComponent(ModifyedNamejTextField)
                            .addComponent(ModifyedTelephoneNumberjTextField))))
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(ModifyefAccountjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ModifyAccountjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modifyedNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyedNamejTextField))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ModifyedEmailjTextField))
                    .addComponent(modifyedEmailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModifyedTelephoneNumberjTextField)
                    .addComponent(modifyedTelephoneNumberjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78)
                .addComponent(ModifyefAccountjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModifyefAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyefAccountjButtonActionPerformed
        String Name;
        String Email;
        String PhoneNumber;
        Name = ModifyedNamejTextField.getText();
        Email = ModifyedEmailjTextField.getText();
        PhoneNumber = ModifyedTelephoneNumberjTextField.getText();

        if (InputValidation.UernameAddNewAccount(Name)) {
            if (InputValidation.eMailValidation(Email)) {
                if (InputValidation.telephoneVerification(PhoneNumber)) {

                    if (evt.getSource() == ModifyefAccountjButton) {

                        try {
                            ModifyAccount(Name, Email, PhoneNumber);
                        } catch (IOException ex) {
                            Logger.getLogger(ModifyAccountJFrame.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                    new HomeScreenJFrame().setVisible(true);
                    super.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter a valid phone number", "Message", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter a valid email", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter your First and Last name", "Message", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_ModifyefAccountjButtonActionPerformed

    private void ModifyedNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyedNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyedNamejTextFieldActionPerformed

    private void ModifyedEmailjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyedEmailjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModifyedEmailjTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyAccountJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyAccountJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ModifyAccountjLabel;
    private javax.swing.JTextField ModifyedEmailjTextField;
    private javax.swing.JTextField ModifyedNamejTextField;
    private javax.swing.JTextField ModifyedTelephoneNumberjTextField;
    private javax.swing.JButton ModifyefAccountjButton;
    private javax.swing.JLabel modifyedEmailjLabel;
    private javax.swing.JLabel modifyedNamejLabel;
    private javax.swing.JLabel modifyedTelephoneNumberjLabel;
    // End of variables declaration//GEN-END:variables
}
