/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SearchAccountsJFrame extends javax.swing.JFrame {

    static String filepath = "accounts.txt";

    /**
     * Creates new form SearchAccountsJFrame
     */
    public SearchAccountsJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstjPanel = new javax.swing.JPanel();
        searchkeywordjTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SearchjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchAccountsjTable = new javax.swing.JTable();
        secondjPanel = new javax.swing.JPanel();
        backtoMainMenuFromSearchjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        searchkeywordjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchkeywordjTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Name");

        SearchjButton.setText("Search");
        SearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchjButtonActionPerformed(evt);
            }
        });

        searchAccountsjTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchAccountsjTable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        searchAccountsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acc No", "Name", "Balance", "E-Mail", "Date opened", "Tel No", "Type"
            }
        ));
        searchAccountsjTable.setToolTipText("");
        jScrollPane1.setViewportView(searchAccountsjTable);

        javax.swing.GroupLayout firstjPanelLayout = new javax.swing.GroupLayout(firstjPanel);
        firstjPanel.setLayout(firstjPanelLayout);
        firstjPanelLayout.setHorizontalGroup(
            firstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstjPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchkeywordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        firstjPanelLayout.setVerticalGroup(
            firstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstjPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(firstjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchkeywordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout secondjPanelLayout = new javax.swing.GroupLayout(secondjPanel);
        secondjPanel.setLayout(secondjPanelLayout);
        secondjPanelLayout.setHorizontalGroup(
            secondjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        secondjPanelLayout.setVerticalGroup(
            secondjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        backtoMainMenuFromSearchjButton.setText("Back to Main Menu");
        backtoMainMenuFromSearchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMainMenuFromSearchjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(firstjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(665, 665, 665)
                .addComponent(secondjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backtoMainMenuFromSearchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(firstjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backtoMainMenuFromSearchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(secondjPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchjButtonActionPerformed
        String keyword;
        keyword = searchkeywordjTextField.getText().trim();
        if (InputValidation.usernameValidationForSearch(keyword)) {

            int count = 0;
            if (evt.getSource() == SearchjButton) {
                DefaultTableModel model = (DefaultTableModel) searchAccountsjTable.getModel();
                model.setRowCount(0);
                try {
                    List<String> lines = Files.readAllLines(Paths.get(filepath));
                    for (String line : lines) {
                        //System.out.println(line);
                        String accountDetails[] = line.split(",");
                        String accNo = accountDetails[0];
                        String name = accountDetails[1];
                        String nameParts[] = name.split(" ");
                        String firstName = nameParts[0];
                        String lastName = nameParts[1];
                        String Balance = accountDetails[2];
                        String email = accountDetails[3];
                        String DateOpened = accountDetails[4];
                        String telno = accountDetails[5];
                        String type = accountDetails[6];
                        if (keyword.equalsIgnoreCase(firstName) || keyword.equalsIgnoreCase(lastName)) {
                            model.addRow(new Object[]{accNo, name, Balance, email, DateOpened, telno, type});
                            accNo = "";
                            name = "";
                            Balance = "";
                            email = "";
                            DateOpened = "";
                            telno = "";
                            type = "";
                            count++;
                        }
                    }
                    if (count == 0) {
                        model.addRow(new Object[]{"NO matches are found"});
                    }
                } catch (IOException e) {
                    System.out.println("Error occured while reading file");
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Enter a valid name", "Message", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_SearchjButtonActionPerformed

    private void searchkeywordjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchkeywordjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchkeywordjTextFieldActionPerformed

    private void backtoMainMenuFromSearchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMainMenuFromSearchjButtonActionPerformed
        SearchAccountsJFrame.this.setVisible(false);
        new HomeScreenJFrame().setVisible(true);
    }//GEN-LAST:event_backtoMainMenuFromSearchjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchAccountsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchjButton;
    private javax.swing.JButton backtoMainMenuFromSearchjButton;
    private javax.swing.JPanel firstjPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable searchAccountsjTable;
    private javax.swing.JTextField searchkeywordjTextField;
    private javax.swing.JPanel secondjPanel;
    // End of variables declaration//GEN-END:variables
}
