package pkgfinal.project;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class ViewAccountsJFrame extends javax.swing.JFrame {

    static String filepath = "accounts.txt";

    public JButton getBackMainMenuFromViewjButton() {
        return BackMainMenuFromViewjButton;
    }

    public JComboBox<String> getjComboBox() {
        return jComboBox;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * Creates new form ViewAccountsJFrame
     */
    public ViewAccountsJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) viewAccountsjTable.getModel();
        List<String> lines = new ArrayList<String>();
        try {
            lines = Files.readAllLines(Paths.get(filepath));
        } catch (IOException ex) {
            Logger.getLogger(ViewAccountsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String line : lines) {
            String accountDetails[] = line.split(",");
            String accNo = accountDetails[0];
            String name = accountDetails[1];
            String nameParts[] = name.split(" ");
            String Balance = accountDetails[2];
            String email = accountDetails[3];
            String DateOpened = accountDetails[4];
            String telno = accountDetails[5];
            String type = accountDetails[6];
            model.addRow(new Object[]{accNo, name, Balance, email, telno, DateOpened, type});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewAccountsjTable = new javax.swing.JTable();
        BackMainMenuFromViewjButton = new javax.swing.JButton();
        jComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accounts Details");

        viewAccountsjTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewAccountsjTable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        viewAccountsjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Acc No", "Name", "E-mail", "Balance", "Date opened", "Tel No", "Type"
            }
        ));
        viewAccountsjTable.setToolTipText("");
        jScrollPane1.setViewportView(viewAccountsjTable);
        viewAccountsjTable.getAccessibleContext().setAccessibleName("viewAccountsjTable\n");

        BackMainMenuFromViewjButton.setText("Back to Main Menu");
        BackMainMenuFromViewjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMainMenuFromViewjButtonActionPerformed(evt);
            }
        });

        jComboBox.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Names", "Balance", "Date opened" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Sorting based on");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BackMainMenuFromViewjButton)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BackMainMenuFromViewjButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMainMenuFromViewjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMainMenuFromViewjButtonActionPerformed
        ViewAccountsJFrame.this.setVisible(false);         new HomeScreenJFrame().setVisible(true);    }//GEN-LAST:event_BackMainMenuFromViewjButtonActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed
        String selectedOption = jComboBox.getSelectedItem().toString();
        DefaultTableModel model = (DefaultTableModel) viewAccountsjTable.getModel();
        List<String> lines = new ArrayList<String>();

        try {
            lines = Files.readAllLines(Paths.get(filepath));
        } catch (IOException ex) {
            Logger.getLogger(ViewAccountsJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        model.setRowCount(0);
        switch (selectedOption) {
            case "Names":
                lines = Sorting.sortingByNames();
                break;
            case "Balance":
//                System.out.println("in balance");
                lines = Sorting.sortingByBalance();
                break;
            case "Date opened":
                lines = Sorting.sortingByDateOpened();
                break;
            default: {
            }

        }
        for (String line : lines) {
            String accountDetails[] = line.split(",");
            String accNo = accountDetails[0];
            String name = accountDetails[1];
            String nameParts[] = name.split(" ");
            String Balance = accountDetails[2];
            String email = accountDetails[3];
            String DateOpened = accountDetails[4];
            String telno = accountDetails[5];
            String type = accountDetails[6];
            model.addRow(new Object[]{accNo, name, Balance, email, telno, DateOpened, type});
        }


    }//GEN-LAST:event_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAccountsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAccountsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackMainMenuFromViewjButton;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewAccountsjTable;
    // End of variables declaration//GEN-END:variables

    public JTable getViewAccountsjTable() {
        return viewAccountsjTable;
    }

}
