/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal.project;

import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pkgfinal.project.ModifyWithdraw.WithdrawCurrent;
import static pkgfinal.project.ModifyWithdraw.WithdrawSavings;


public class WithdrawJFrame extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawJFrame
     */
    public WithdrawJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        withdrawAmountJTextField = new javax.swing.JTextField();
        withdrawAccountNumberJTextField = new javax.swing.JTextField();
        withdrawJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Withdraw");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("Account Number");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("Amount to be withdrawed");

        withdrawJButton.setText("Withdraw");
        withdrawJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(withdrawJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(withdrawAmountJTextField)
                                    .addComponent(withdrawAccountNumberJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawAccountNumberJTextField))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(withdrawAmountJTextField)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(withdrawJButton)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawJButtonActionPerformed
        String accountNumber;
        String amountToBeWithdrowed;
        LocalDateTime currentTime = LocalDateTime.now();
        String currentT = String.valueOf(currentTime);
        accountNumber = withdrawAccountNumberJTextField.getText();
        amountToBeWithdrowed = withdrawAmountJTextField.getText();
        if (InputValidation.accountNumberValidation(accountNumber)) {
            if (InputValidation.moenyvalidation(amountToBeWithdrowed)) {

                if (evt.getSource() == withdrawJButton) {
                    try {

                        boolean checkValidation = Account.validateAccountExcistance(accountNumber);
                        double amount = Double.parseDouble(amountToBeWithdrowed);
                        if (checkValidation == false) {
                            JOptionPane.showMessageDialog(this, "Non excisting account.", "Message", JOptionPane.ERROR_MESSAGE);
                        } else if (checkValidation == true) {
                            if (amount > 10000.0) {
                                JOptionPane.showMessageDialog(this, "Amount withdrawed exceeds 10K$, please deposit less.", "Message", JOptionPane.INFORMATION_MESSAGE);
                            } else if (amount < 10000.0 && amount > 0.0) {
                                if (amount < 1000.0) {
                                    //10$ fee if current acc then modify giovanni
                                    WithdrawCurrent(amountToBeWithdrowed, accountNumber);

                                    Transaction.AddTransactionInfo("withdraw", amountToBeWithdrowed, accountNumber, currentT);
                                } else {

                                    //modify giovanni
                                    WithdrawSavings(amountToBeWithdrowed, accountNumber);

                                    Transaction.AddTransactionInfo("withdraw", amountToBeWithdrowed, accountNumber, currentT);
                                }
                            } else {
                                JOptionPane.showMessageDialog(this, "Incorrect Amount", "Message", JOptionPane.ERROR_MESSAGE);
                            }
                        }

                    } catch (Exception ex) {
                        System.out.println("Error 404");
                    }
                }
                super.dispose();
                new HomeScreenJFrame().setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Input a valid amount", "Message", JOptionPane.ERROR_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Input a valid account", "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_withdrawJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithdrawJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithdrawJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithdrawJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithdrawJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithdrawJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField withdrawAccountNumberJTextField;
    private javax.swing.JTextField withdrawAmountJTextField;
    private javax.swing.JButton withdrawJButton;
    // End of variables declaration//GEN-END:variables
}
